# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Alarme(object):
    def setupUi(self, Alarme):
        Alarme.setObjectName("Alarme")
        Alarme.resize(400, 300)
        Alarme.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.pushButton = QtWidgets.QPushButton(Alarme)
        self.pushButton.setGeometry(QtCore.QRect(160, 170, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.spinBox = QtWidgets.QSpinBox(Alarme)
        self.spinBox.setGeometry(QtCore.QRect(180, 90, 71, 22))
        self.spinBox.setMaximum(23)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(Alarme)
        self.spinBox_2.setGeometry(QtCore.QRect(180, 120, 71, 22))
        self.spinBox_2.setMaximum(59)
        self.spinBox_2.setObjectName("spinBox_2")
        self.label = QtWidgets.QLabel(Alarme)
        self.label.setGeometry(QtCore.QRect(140, 90, 31, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Alarme)
        self.label_2.setGeometry(QtCore.QRect(140, 120, 31, 21))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Alarme)
        QtCore.QMetaObject.connectSlotsByName(Alarme)
        Alarme.setTabOrder(self.spinBox, self.spinBox_2)
        Alarme.setTabOrder(self.spinBox_2, self.pushButton)

    def retranslateUi(self, Alarme):
        _translate = QtCore.QCoreApplication.translate
        Alarme.setWindowTitle(_translate("Alarme", "Alarme"))
        self.pushButton.setText(_translate("Alarme", "Alarmar"))
        self.spinBox_2.setWhatsThis(_translate("Alarme", "<html><head/><body><p><br/></p><p><br/></p></body></html>"))
        self.label.setText(_translate("Alarme", "Hora"))
        self.label_2.setText(_translate("Alarme", "Minuto"))
